UPDATE shows SET title = "How I Met Your Mother" WHERE title = "How i met your mother";
SELECT * FROM shows ORDER BY title;
UPDATE shows SET title = "Adventure Time" WHERE title LIKE "adventure";
UPDATE shows SET title = "Arrow" WHERE title LIKE "arrow";
UPDATE shows SET title = "Avatar: The Last Airbender" WHERE title LIKE "Avatar%";
'--' LIKE is not case sensitive !
UPDATE shows SET title = "Brooklyn Nine-Nine" WHERE title LIKE "b99";
UPDATE shows SET title = "Brooklyn Nine-Nine" WHERE title LIKE "brooklyn%";
UPDATE shows SET title = "Community" WHERE title LIKE "community";
UPDATE shows SET title = "Family Guy" WHERE title LIKE "family Guy";
UPDATE shows SET title = "Friends" WHERE title LIKE "friends";
UPDATE shows SET title = "Game Of Thrones" WHERE title LIKE "GoT";
UPDATE shows SET title = "Gilmore Girls" WHERE title LIKE "Girlmore%";
UPDATE shows SET title = "Grey’s Anatomy" WHERE title LIKE "Grey%";
UPDATE shows SET title = "It’s Always Sunny in Philadelphia" WHERE title LIKE "Its%";
UPDATE shows SET title = "Parks and Recreation" WHERE title LIKE "Parks%";
UPDATE shows SET title = "Sherlock" WHERE title LIKE "sherlock%";
UPDATE shows SET title = "Squid Game" WHERE title LIKE "squid%";
UPDATE shows SET title = "The Bachelorette" WHERE title LIKE "The bach%";
UPDATE shows SET title = "The Crown" WHERE title LIKE "The crown%";
UPDATE shows SET title = "The Office" WHERE title LIKE "The office%";
UPDATE shows SET title = "The Office" WHERE title LIKE "office%";
UPDATE shows SET title = "The Queen’s Gambit" WHERE title LIKE "queen%";
UPDATE shows SET title ="The Untamed" WHERE title LIKE "the Untamed";
